# Use root/example as user/password credentials

version: '3'

services:
  joomla:
    image: joomla
    volumes:
      - ./drupal:/app
    restart: always
    links:
      - db:mariadb
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_PASSWORD: example

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080